package com.artemkudryavtsev.newsapp.settings.languageandregion

object Countries {
    val countries = listOf(
        Pair("ae", "United Arab Emirates"),
        Pair("ar", "Argentina"),
        Pair("at", "Austria"),
        Pair("au", "Australia"),
        Pair("be", "Belgium"),
        Pair("bg", "Bulgaria"),
        Pair("br", "Brazil"),
        Pair("ca", "Canada"),
        Pair("ch", "Switzerland"),
        Pair("cn", "China"),
        Pair("co", "Colombia"),
        Pair("cu", "Cuba"),
        Pair("cz", "Czechia"),
        Pair("de", "Germany"),
        Pair("eg", "Egypt"),
        Pair("fr", "France"),
        Pair("gb", "United Kingdom of Great Britain and Northern Ireland"),
        Pair("gr", "Greece"),
        Pair("hk", "Hong Kong"),
        Pair("hu", "Hungary"),
        Pair("id", "Indonesia"),
        Pair("ie", "Ireland"),
        Pair("il", "Israel"),
        Pair("in", "India"),
        Pair("it", "Italy"),
        Pair("jp", "Japan"),
        Pair("kr", "Republic of Korea"),
        Pair("lt", "Lithuania"),
        Pair("lv", "Latvia"),
        Pair("ma", "Morocco"),
        Pair("mx", "Mexico"),
        Pair("my", "Malaysia"),
        Pair("ng", "Nigeria"),
        Pair("nl", "Netherlands"),
        Pair("no", "Norway"),
        Pair("nz", "New Zealand"),
        Pair("ph", "Philippines"),
        Pair("pl", "Poland"),
        Pair("pt", "Portugal"),
        Pair("ro", "Romania"),
        Pair("rs", "Serbia"),
        Pair("ru", "Russian Federation"),
        Pair("sa", "Saudi Arabia"),
        Pair("se", "Sweden"),
        Pair("sg", "Singapore"),
        Pair("si", "Slovenia"),
        Pair("sk", "Slovakia"),
        Pair("th", "Thailand"),
        Pair("tr", "Turkey"),
        Pair("tw", "Taiwan"),
        Pair("ua", "Ukraine"),
        Pair("us", "United States of America"),
        Pair("ve", "Venezuela"),
        Pair("za", "South Africa")
    )
}
